# -*- coding: utf-8 -*-
"""Hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/175Q0FAIREFQF3vcvRL57KQfNhRD9D0T-
"""

print('Hello')

